[pytest]
pythonpath = core

DJANGO_SETTINGS_MODULE = core.settings.development

testpaths = core/tests

python_files = test_*.py *_test.py tests.py

python_classes = Test* *Tests
python_functions = test_*

addopts = 
    -v
    --strict-markers
    --no-migrations
    --reuse-db

norecursedirs = 
    venv
    .git
    staticfiles
    media