# Generated by Django 4.2.30 on 2026-09-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug_tag_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
